scrape_configs:
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['exporter-svc.postgres.svc.cluster.local:9187']
  - job_name: 'ecommerce'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-svc.app.svc.cluster.local:8080']